### ISSUE TITLE
HypernymExtractor module: Not correct RDF output in hypoutput.log.dbpedia file

### ISSUE THREAD

**Issue by m1ci** [KIZI/LinkedHypernymsDataset#1]
The triples in the hypoutput.log.dbpedia file are not correctly RDF formatted. Examples:

&lt;http://dbpedia.org/resource/Autism&gt; &lt;?&gt; &lt;http://dbpedia.org/resource/Disorder&gt;.
&lt;http://dbpedia.org/resource/Achilles&gt; &lt;?&gt; &lt;http://dbpedia.org/resource/Hero&gt;.
&lt;http://dbpedia.org/resource/An_American_in_Paris&gt; &lt;?&gt; &lt;http://dbpedia.org/resource/Poem&gt;.

Errors:
- predicate &lt;?&gt; -- should be rdf:type predicate
- dot (.) at the end -- should be space after the object

**Comment by kliegr** [comment]
"<?>" is generated in the saveHypernym method of CorpusBuilderPR to indicate that the predicate (rdfs:subclassOf, rdf:type) needs to be detected by subsequent processing in THDTypeInferrer.

Since "hypoutput.log.dbpedia" was designed as an intermediate output file, it does no need to necessarily correctly formatted. Nevertheless, this  might confuse users.  Perhaps hypoutput.log.dbpedia could be deleted in the final cleanup phase?

**Comment by propi** [comment]
This is only an auxiliary file - not the final output result. After an extraction process all temporary files can be packed to a .zip file. Main resulting files remain in the output directory and are valid.
