### ISSUE TITLE
remove approximate mapping from LHD 1.0

### ISSUE THREAD

**Issue by kliegr** [KIZI/LinkedHypernymsDataset#2]
LHD assigns some triples with a type in a dbpedia.org/resource namespace to *mapped files based on the presence of this type in the class.superclass.nt file. This file is generated using a simple string-based ontology alignment algorithm, and is assumed to be manually curated into the .confirmed file. Since in LHD2.0 type inference is handled fully automatically, the whole process of generating "class.superclass.nt" file should be removed from the generation framework, along with the code that checks the presence of the type in this file for determining whether a type is mapped or not.

**Comment by propi** [comment]
Now, in branch v2-develop (later in master), the files: class.subclass.nt and class.superclass.nt are still generated by the extraction framework, but these files are not being used within the string-match mapping or STI. For the string-match mapping only class.equivallence.nt is used. So since now, the .confirmed file is not supported anymore.
